version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: sa
      POSTGRES_DB: portal_proveedores
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  user-service:
    build: ./user-service
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    develop:
      watch:
        - action: sync
          path: ./user-service
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    command: npm start

  order-service:
    build: ./order-service
    volumes:
      - ./order-service:/app/order-service
    ports:
      - "3002:3002"
    depends_on:
      - postgres
    develop:
      watch:
        - action: sync
          path: ./order-service
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    command: npm start

  invoice-service:
    build: ./invoice-service
    volumes:
      - ./invoice-service:/app/invoice-service
    ports:
      - "3003:3003"
    depends_on:
      - postgres
    develop:
      watch:
        - action: sync
          path: ./invoice-service
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
      command: npm start
  
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: ./frontend
          tty: true
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    command: npm start

volumes:
  pgdata:
